// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 16 Aug 2016 23:40:46 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package spirv

const (
	// Version as defined in spirv/spirv.h:53
	Version = 0x10100
	// Revision as defined in spirv/spirv.h:54
	Revision = 3
)

// SourceLanguage as declared in spirv/spirv.h:69
type SourceLanguage int32

// SourceLanguage enumeration from spirv/spirv.h:69
const (
	SourceLanguageUnknown    SourceLanguage = iota
	SourceLanguageESSL       SourceLanguage = 1
	SourceLanguageGLSL       SourceLanguage = 2
	SourceLanguageOpenCL_C   SourceLanguage = 3
	SourceLanguageOpenCL_CPP SourceLanguage = 4
	SourceLanguageMax        SourceLanguage = 2147483647
)

// ExecutionModel as declared in spirv/spirv.h:80
type ExecutionModel int32

// ExecutionModel enumeration from spirv/spirv.h:80
const (
	ExecutionModelVertex                 ExecutionModel = iota
	ExecutionModelTessellationControl    ExecutionModel = 1
	ExecutionModelTessellationEvaluation ExecutionModel = 2
	ExecutionModelGeometry               ExecutionModel = 3
	ExecutionModelFragment               ExecutionModel = 4
	ExecutionModelGLCompute              ExecutionModel = 5
	ExecutionModelKernel                 ExecutionModel = 6
	ExecutionModelMax                    ExecutionModel = 2147483647
)

// AddressingModel as declared in spirv/spirv.h:87
type AddressingModel int32

// AddressingModel enumeration from spirv/spirv.h:87
const (
	AddressingModelLogical    AddressingModel = iota
	AddressingModelPhysical32 AddressingModel = 1
	AddressingModelPhysical64 AddressingModel = 2
	AddressingModelMax        AddressingModel = 2147483647
)

// MemoryModel as declared in spirv/spirv.h:94
type MemoryModel int32

// MemoryModel enumeration from spirv/spirv.h:94
const (
	MemoryModelSimple  MemoryModel = iota
	MemoryModelGLSL450 MemoryModel = 1
	MemoryModelOpenCL  MemoryModel = 2
	MemoryModelMax     MemoryModel = 2147483647
)

// ExecutionMode as declared in spirv/spirv.h:133
type ExecutionMode int32

// ExecutionMode enumeration from spirv/spirv.h:133
const (
	ExecutionModeInvocations             ExecutionMode = iota
	ExecutionModeSpacingEqual            ExecutionMode = 1
	ExecutionModeSpacingFractionalEven   ExecutionMode = 2
	ExecutionModeSpacingFractionalOdd    ExecutionMode = 3
	ExecutionModeVertexOrderCw           ExecutionMode = 4
	ExecutionModeVertexOrderCcw          ExecutionMode = 5
	ExecutionModePixelCenterInteger      ExecutionMode = 6
	ExecutionModeOriginUpperLeft         ExecutionMode = 7
	ExecutionModeOriginLowerLeft         ExecutionMode = 8
	ExecutionModeEarlyFragmentTests      ExecutionMode = 9
	ExecutionModePointMode               ExecutionMode = 10
	ExecutionModeXfb                     ExecutionMode = 11
	ExecutionModeDepthReplacing          ExecutionMode = 12
	ExecutionModeDepthGreater            ExecutionMode = 14
	ExecutionModeDepthLess               ExecutionMode = 15
	ExecutionModeDepthUnchanged          ExecutionMode = 16
	ExecutionModeLocalSize               ExecutionMode = 17
	ExecutionModeLocalSizeHint           ExecutionMode = 18
	ExecutionModeInputPoints             ExecutionMode = 19
	ExecutionModeInputLines              ExecutionMode = 20
	ExecutionModeInputLinesAdjacency     ExecutionMode = 21
	ExecutionModeTriangles               ExecutionMode = 22
	ExecutionModeInputTrianglesAdjacency ExecutionMode = 23
	ExecutionModeQuads                   ExecutionMode = 24
	ExecutionModeIsolines                ExecutionMode = 25
	ExecutionModeOutputVertices          ExecutionMode = 26
	ExecutionModeOutputPoints            ExecutionMode = 27
	ExecutionModeOutputLineStrip         ExecutionMode = 28
	ExecutionModeOutputTriangleStrip     ExecutionMode = 29
	ExecutionModeVecTypeHint             ExecutionMode = 30
	ExecutionModeContractionOff          ExecutionMode = 31
	ExecutionModeInitializer             ExecutionMode = 33
	ExecutionModeFinalizer               ExecutionMode = 34
	ExecutionModeSubgroupSize            ExecutionMode = 35
	ExecutionModeSubgroupsPerWorkgroup   ExecutionMode = 36
	ExecutionModeMax                     ExecutionMode = 2147483647
)

// StorageClass as declared in spirv/spirv.h:149
type StorageClass int32

// StorageClass enumeration from spirv/spirv.h:149
const (
	StorageClassUniformConstant StorageClass = iota
	StorageClassInput           StorageClass = 1
	StorageClassUniform         StorageClass = 2
	StorageClassOutput          StorageClass = 3
	StorageClassWorkgroup       StorageClass = 4
	StorageClassCrossWorkgroup  StorageClass = 5
	StorageClassPrivate         StorageClass = 6
	StorageClassFunction        StorageClass = 7
	StorageClassGeneric         StorageClass = 8
	StorageClassPushConstant    StorageClass = 9
	StorageClassAtomicCounter   StorageClass = 10
	StorageClassImage           StorageClass = 11
	StorageClassMax             StorageClass = 2147483647
)

// Dim as declared in spirv/spirv.h:160
type Dim int32

// Dim enumeration from spirv/spirv.h:160
const (
	Dim1D          Dim = iota
	Dim2D          Dim = 1
	Dim3D          Dim = 2
	DimCube        Dim = 3
	DimRect        Dim = 4
	DimBuffer      Dim = 5
	DimSubpassData Dim = 6
	DimMax         Dim = 2147483647
)

// SamplerAddressingMode as declared in spirv/spirv.h:169
type SamplerAddressingMode int32

// SamplerAddressingMode enumeration from spirv/spirv.h:169
const (
	SamplerAddressingModeNone           SamplerAddressingMode = iota
	SamplerAddressingModeClampToEdge    SamplerAddressingMode = 1
	SamplerAddressingModeClamp          SamplerAddressingMode = 2
	SamplerAddressingModeRepeat         SamplerAddressingMode = 3
	SamplerAddressingModeRepeatMirrored SamplerAddressingMode = 4
	SamplerAddressingModeMax            SamplerAddressingMode = 2147483647
)

// SamplerFilterMode as declared in spirv/spirv.h:175
type SamplerFilterMode int32

// SamplerFilterMode enumeration from spirv/spirv.h:175
const (
	SamplerFilterModeNearest SamplerFilterMode = iota
	SamplerFilterModeLinear  SamplerFilterMode = 1
	SamplerFilterModeMax     SamplerFilterMode = 2147483647
)

// ImageFormat as declared in spirv/spirv.h:219
type ImageFormat int32

// ImageFormat enumeration from spirv/spirv.h:219
const (
	ImageFormatUnknown      ImageFormat = iota
	ImageFormatRgba32f      ImageFormat = 1
	ImageFormatRgba16f      ImageFormat = 2
	ImageFormatR32f         ImageFormat = 3
	ImageFormatRgba8        ImageFormat = 4
	ImageFormatRgba8Snorm   ImageFormat = 5
	ImageFormatRg32f        ImageFormat = 6
	ImageFormatRg16f        ImageFormat = 7
	ImageFormatR11fG11fB10f ImageFormat = 8
	ImageFormatR16f         ImageFormat = 9
	ImageFormatRgba16       ImageFormat = 10
	ImageFormatRgb10A2      ImageFormat = 11
	ImageFormatRg16         ImageFormat = 12
	ImageFormatRg8          ImageFormat = 13
	ImageFormatR16          ImageFormat = 14
	ImageFormatR8           ImageFormat = 15
	ImageFormatRgba16Snorm  ImageFormat = 16
	ImageFormatRg16Snorm    ImageFormat = 17
	ImageFormatRg8Snorm     ImageFormat = 18
	ImageFormatR16Snorm     ImageFormat = 19
	ImageFormatR8Snorm      ImageFormat = 20
	ImageFormatRgba32i      ImageFormat = 21
	ImageFormatRgba16i      ImageFormat = 22
	ImageFormatRgba8i       ImageFormat = 23
	ImageFormatR32i         ImageFormat = 24
	ImageFormatRg32i        ImageFormat = 25
	ImageFormatRg16i        ImageFormat = 26
	ImageFormatRg8i         ImageFormat = 27
	ImageFormatR16i         ImageFormat = 28
	ImageFormatR8i          ImageFormat = 29
	ImageFormatRgba32ui     ImageFormat = 30
	ImageFormatRgba16ui     ImageFormat = 31
	ImageFormatRgba8ui      ImageFormat = 32
	ImageFormatR32ui        ImageFormat = 33
	ImageFormatRgb10a2ui    ImageFormat = 34
	ImageFormatRg32ui       ImageFormat = 35
	ImageFormatRg16ui       ImageFormat = 36
	ImageFormatRg8ui        ImageFormat = 37
	ImageFormatR16ui        ImageFormat = 38
	ImageFormatR8ui         ImageFormat = 39
	ImageFormatMax          ImageFormat = 2147483647
)

// ImageChannelOrder as declared in spirv/spirv.h:243
type ImageChannelOrder int32

// ImageChannelOrder enumeration from spirv/spirv.h:243
const (
	ImageChannelOrderR            ImageChannelOrder = iota
	ImageChannelOrderA            ImageChannelOrder = 1
	ImageChannelOrderRG           ImageChannelOrder = 2
	ImageChannelOrderRA           ImageChannelOrder = 3
	ImageChannelOrderRGB          ImageChannelOrder = 4
	ImageChannelOrderRGBA         ImageChannelOrder = 5
	ImageChannelOrderBGRA         ImageChannelOrder = 6
	ImageChannelOrderARGB         ImageChannelOrder = 7
	ImageChannelOrderIntensity    ImageChannelOrder = 8
	ImageChannelOrderLuminance    ImageChannelOrder = 9
	ImageChannelOrderRx           ImageChannelOrder = 10
	ImageChannelOrderRGx          ImageChannelOrder = 11
	ImageChannelOrderRGBx         ImageChannelOrder = 12
	ImageChannelOrderDepth        ImageChannelOrder = 13
	ImageChannelOrderDepthStencil ImageChannelOrder = 14
	ImageChannelOrdersRGB         ImageChannelOrder = 15
	ImageChannelOrdersRGBx        ImageChannelOrder = 16
	ImageChannelOrdersRGBA        ImageChannelOrder = 17
	ImageChannelOrdersBGRA        ImageChannelOrder = 18
	ImageChannelOrderABGR         ImageChannelOrder = 19
	ImageChannelOrderMax          ImageChannelOrder = 2147483647
)

// ImageChannelDataType as declared in spirv/spirv.h:264
type ImageChannelDataType int32

// ImageChannelDataType enumeration from spirv/spirv.h:264
const (
	ImageChannelDataTypeSnormInt8        ImageChannelDataType = iota
	ImageChannelDataTypeSnormInt16       ImageChannelDataType = 1
	ImageChannelDataTypeUnormInt8        ImageChannelDataType = 2
	ImageChannelDataTypeUnormInt16       ImageChannelDataType = 3
	ImageChannelDataTypeUnormShort565    ImageChannelDataType = 4
	ImageChannelDataTypeUnormShort555    ImageChannelDataType = 5
	ImageChannelDataTypeUnormInt101010   ImageChannelDataType = 6
	ImageChannelDataTypeSignedInt8       ImageChannelDataType = 7
	ImageChannelDataTypeSignedInt16      ImageChannelDataType = 8
	ImageChannelDataTypeSignedInt32      ImageChannelDataType = 9
	ImageChannelDataTypeUnsignedInt8     ImageChannelDataType = 10
	ImageChannelDataTypeUnsignedInt16    ImageChannelDataType = 11
	ImageChannelDataTypeUnsignedInt32    ImageChannelDataType = 12
	ImageChannelDataTypeHalfFloat        ImageChannelDataType = 13
	ImageChannelDataTypeFloat            ImageChannelDataType = 14
	ImageChannelDataTypeUnormInt24       ImageChannelDataType = 15
	ImageChannelDataTypeUnormInt101010_2 ImageChannelDataType = 16
	ImageChannelDataTypeMax              ImageChannelDataType = 2147483647
)

// ImageOperandsShift as declared in spirv/spirv.h:276
type ImageOperandsShift int32

// ImageOperandsShift enumeration from spirv/spirv.h:276
const (
	ImageOperandsBiasShift         ImageOperandsShift = iota
	ImageOperandsLodShift          ImageOperandsShift = 1
	ImageOperandsGradShift         ImageOperandsShift = 2
	ImageOperandsConstOffsetShift  ImageOperandsShift = 3
	ImageOperandsOffsetShift       ImageOperandsShift = 4
	ImageOperandsConstOffsetsShift ImageOperandsShift = 5
	ImageOperandsSampleShift       ImageOperandsShift = 6
	ImageOperandsMinLodShift       ImageOperandsShift = 7
	ImageOperandsMax               ImageOperandsShift = 2147483647
)

// ImageOperandsMask as declared in spirv/spirv.h:288
type ImageOperandsMask int32

// ImageOperandsMask enumeration from spirv/spirv.h:288
const (
	ImageOperandsMaskNone         ImageOperandsMask = iota
	ImageOperandsBiasMask         ImageOperandsMask = 1
	ImageOperandsLodMask          ImageOperandsMask = 2
	ImageOperandsGradMask         ImageOperandsMask = 4
	ImageOperandsConstOffsetMask  ImageOperandsMask = 8
	ImageOperandsOffsetMask       ImageOperandsMask = 16
	ImageOperandsConstOffsetsMask ImageOperandsMask = 32
	ImageOperandsSampleMask       ImageOperandsMask = 64
	ImageOperandsMinLodMask       ImageOperandsMask = 128
)

// FPFastMathModeShift as declared in spirv/spirv.h:297
type FPFastMathModeShift int32

// FPFastMathModeShift enumeration from spirv/spirv.h:297
const (
	FPFastMathModeNotNaNShift     FPFastMathModeShift = iota
	FPFastMathModeNotInfShift     FPFastMathModeShift = 1
	FPFastMathModeNSZShift        FPFastMathModeShift = 2
	FPFastMathModeAllowRecipShift FPFastMathModeShift = 3
	FPFastMathModeFastShift       FPFastMathModeShift = 4
	FPFastMathModeMax             FPFastMathModeShift = 2147483647
)

// FPFastMathModeMask as declared in spirv/spirv.h:306
type FPFastMathModeMask int32

// FPFastMathModeMask enumeration from spirv/spirv.h:306
const (
	FPFastMathModeMaskNone       FPFastMathModeMask = iota
	FPFastMathModeNotNaNMask     FPFastMathModeMask = 1
	FPFastMathModeNotInfMask     FPFastMathModeMask = 2
	FPFastMathModeNSZMask        FPFastMathModeMask = 4
	FPFastMathModeAllowRecipMask FPFastMathModeMask = 8
	FPFastMathModeFastMask       FPFastMathModeMask = 16
)

// FPRoundingMode as declared in spirv/spirv.h:314
type FPRoundingMode int32

// FPRoundingMode enumeration from spirv/spirv.h:314
const (
	FPRoundingModeRTE FPRoundingMode = iota
	FPRoundingModeRTZ FPRoundingMode = 1
	FPRoundingModeRTP FPRoundingMode = 2
	FPRoundingModeRTN FPRoundingMode = 3
	FPRoundingModeMax FPRoundingMode = 2147483647
)

// LinkageType as declared in spirv/spirv.h:320
type LinkageType int32

// LinkageType enumeration from spirv/spirv.h:320
const (
	LinkageTypeExport LinkageType = iota
	LinkageTypeImport LinkageType = 1
	LinkageTypeMax    LinkageType = 2147483647
)

// AccessQualifier as declared in spirv/spirv.h:327
type AccessQualifier int32

// AccessQualifier enumeration from spirv/spirv.h:327
const (
	AccessQualifierReadOnly  AccessQualifier = iota
	AccessQualifierWriteOnly AccessQualifier = 1
	AccessQualifierReadWrite AccessQualifier = 2
	AccessQualifierMax       AccessQualifier = 2147483647
)

// FunctionParameterAttribute as declared in spirv/spirv.h:339
type FunctionParameterAttribute int32

// FunctionParameterAttribute enumeration from spirv/spirv.h:339
const (
	FunctionParameterAttributeZext        FunctionParameterAttribute = iota
	FunctionParameterAttributeSext        FunctionParameterAttribute = 1
	FunctionParameterAttributeByVal       FunctionParameterAttribute = 2
	FunctionParameterAttributeSret        FunctionParameterAttribute = 3
	FunctionParameterAttributeNoAlias     FunctionParameterAttribute = 4
	FunctionParameterAttributeNoCapture   FunctionParameterAttribute = 5
	FunctionParameterAttributeNoWrite     FunctionParameterAttribute = 6
	FunctionParameterAttributeNoReadWrite FunctionParameterAttribute = 7
	FunctionParameterAttributeMax         FunctionParameterAttribute = 2147483647
)

// Decoration as declared in spirv/spirv.h:387
type Decoration int32

// Decoration enumeration from spirv/spirv.h:387
const (
	DecorationRelaxedPrecision     Decoration = iota
	DecorationSpecId               Decoration = 1
	DecorationBlock                Decoration = 2
	DecorationBufferBlock          Decoration = 3
	DecorationRowMajor             Decoration = 4
	DecorationColMajor             Decoration = 5
	DecorationArrayStride          Decoration = 6
	DecorationMatrixStride         Decoration = 7
	DecorationGLSLShared           Decoration = 8
	DecorationGLSLPacked           Decoration = 9
	DecorationCPacked              Decoration = 10
	DecorationBuiltIn              Decoration = 11
	DecorationNoPerspective        Decoration = 13
	DecorationFlat                 Decoration = 14
	DecorationPatch                Decoration = 15
	DecorationCentroid             Decoration = 16
	DecorationSample               Decoration = 17
	DecorationInvariant            Decoration = 18
	DecorationRestrict             Decoration = 19
	DecorationAliased              Decoration = 20
	DecorationVolatile             Decoration = 21
	DecorationConstant             Decoration = 22
	DecorationCoherent             Decoration = 23
	DecorationNonWritable          Decoration = 24
	DecorationNonReadable          Decoration = 25
	DecorationUniform              Decoration = 26
	DecorationSaturatedConversion  Decoration = 28
	DecorationStream               Decoration = 29
	DecorationLocation             Decoration = 30
	DecorationComponent            Decoration = 31
	DecorationIndex                Decoration = 32
	DecorationBinding              Decoration = 33
	DecorationDescriptorSet        Decoration = 34
	DecorationOffset               Decoration = 35
	DecorationXfbBuffer            Decoration = 36
	DecorationXfbStride            Decoration = 37
	DecorationFuncParamAttr        Decoration = 38
	DecorationFPRoundingMode       Decoration = 39
	DecorationFPFastMathMode       Decoration = 40
	DecorationLinkageAttributes    Decoration = 41
	DecorationNoContraction        Decoration = 42
	DecorationInputAttachmentIndex Decoration = 43
	DecorationAlignment            Decoration = 44
	DecorationMaxByteOffset        Decoration = 45
	DecorationMax                  Decoration = 2147483647
)

// BuiltIn as declared in spirv/spirv.h:432
type BuiltIn int32

// BuiltIn enumeration from spirv/spirv.h:432
const (
	BuiltInPosition                  BuiltIn = iota
	BuiltInPointSize                 BuiltIn = 1
	BuiltInClipDistance              BuiltIn = 3
	BuiltInCullDistance              BuiltIn = 4
	BuiltInVertexId                  BuiltIn = 5
	BuiltInInstanceId                BuiltIn = 6
	BuiltInPrimitiveId               BuiltIn = 7
	BuiltInInvocationId              BuiltIn = 8
	BuiltInLayer                     BuiltIn = 9
	BuiltInViewportIndex             BuiltIn = 10
	BuiltInTessLevelOuter            BuiltIn = 11
	BuiltInTessLevelInner            BuiltIn = 12
	BuiltInTessCoord                 BuiltIn = 13
	BuiltInPatchVertices             BuiltIn = 14
	BuiltInFragCoord                 BuiltIn = 15
	BuiltInPointCoord                BuiltIn = 16
	BuiltInFrontFacing               BuiltIn = 17
	BuiltInSampleId                  BuiltIn = 18
	BuiltInSamplePosition            BuiltIn = 19
	BuiltInSampleMask                BuiltIn = 20
	BuiltInFragDepth                 BuiltIn = 22
	BuiltInHelperInvocation          BuiltIn = 23
	BuiltInNumWorkgroups             BuiltIn = 24
	BuiltInWorkgroupSize             BuiltIn = 25
	BuiltInWorkgroupId               BuiltIn = 26
	BuiltInLocalInvocationId         BuiltIn = 27
	BuiltInGlobalInvocationId        BuiltIn = 28
	BuiltInLocalInvocationIndex      BuiltIn = 29
	BuiltInWorkDim                   BuiltIn = 30
	BuiltInGlobalSize                BuiltIn = 31
	BuiltInEnqueuedWorkgroupSize     BuiltIn = 32
	BuiltInGlobalOffset              BuiltIn = 33
	BuiltInGlobalLinearId            BuiltIn = 34
	BuiltInSubgroupSize              BuiltIn = 36
	BuiltInSubgroupMaxSize           BuiltIn = 37
	BuiltInNumSubgroups              BuiltIn = 38
	BuiltInNumEnqueuedSubgroups      BuiltIn = 39
	BuiltInSubgroupId                BuiltIn = 40
	BuiltInSubgroupLocalInvocationId BuiltIn = 41
	BuiltInVertexIndex               BuiltIn = 42
	BuiltInInstanceIndex             BuiltIn = 43
	BuiltInMax                       BuiltIn = 2147483647
)

// SelectionControlShift as declared in spirv/spirv.h:438
type SelectionControlShift int32

// SelectionControlShift enumeration from spirv/spirv.h:438
const (
	SelectionControlFlattenShift     SelectionControlShift = iota
	SelectionControlDontFlattenShift SelectionControlShift = 1
	SelectionControlMax              SelectionControlShift = 2147483647
)

// SelectionControlMask as declared in spirv/spirv.h:444
type SelectionControlMask int32

// SelectionControlMask enumeration from spirv/spirv.h:444
const (
	SelectionControlMaskNone        SelectionControlMask = iota
	SelectionControlFlattenMask     SelectionControlMask = 1
	SelectionControlDontFlattenMask SelectionControlMask = 2
)

// LoopControlShift as declared in spirv/spirv.h:452
type LoopControlShift int32

// LoopControlShift enumeration from spirv/spirv.h:452
const (
	LoopControlUnrollShift             LoopControlShift = iota
	LoopControlDontUnrollShift         LoopControlShift = 1
	LoopControlDependencyInfiniteShift LoopControlShift = 2
	LoopControlDependencyLengthShift   LoopControlShift = 3
	LoopControlMax                     LoopControlShift = 2147483647
)

// LoopControlMask as declared in spirv/spirv.h:460
type LoopControlMask int32

// LoopControlMask enumeration from spirv/spirv.h:460
const (
	LoopControlMaskNone               LoopControlMask = iota
	LoopControlUnrollMask             LoopControlMask = 1
	LoopControlDontUnrollMask         LoopControlMask = 2
	LoopControlDependencyInfiniteMask LoopControlMask = 4
	LoopControlDependencyLengthMask   LoopControlMask = 8
)

// FunctionControlShift as declared in spirv/spirv.h:468
type FunctionControlShift int32

// FunctionControlShift enumeration from spirv/spirv.h:468
const (
	FunctionControlInlineShift     FunctionControlShift = iota
	FunctionControlDontInlineShift FunctionControlShift = 1
	FunctionControlPureShift       FunctionControlShift = 2
	FunctionControlConstShift      FunctionControlShift = 3
	FunctionControlMax             FunctionControlShift = 2147483647
)

// FunctionControlMask as declared in spirv/spirv.h:476
type FunctionControlMask int32

// FunctionControlMask enumeration from spirv/spirv.h:476
const (
	FunctionControlMaskNone       FunctionControlMask = iota
	FunctionControlInlineMask     FunctionControlMask = 1
	FunctionControlDontInlineMask FunctionControlMask = 2
	FunctionControlPureMask       FunctionControlMask = 4
	FunctionControlConstMask      FunctionControlMask = 8
)

// MemorySemanticsShift as declared in spirv/spirv.h:490
type MemorySemanticsShift int32

// MemorySemanticsShift enumeration from spirv/spirv.h:490
const (
	MemorySemanticsAcquireShift                MemorySemanticsShift = 1
	MemorySemanticsReleaseShift                MemorySemanticsShift = 2
	MemorySemanticsAcquireReleaseShift         MemorySemanticsShift = 3
	MemorySemanticsSequentiallyConsistentShift MemorySemanticsShift = 4
	MemorySemanticsUniformMemoryShift          MemorySemanticsShift = 6
	MemorySemanticsSubgroupMemoryShift         MemorySemanticsShift = 7
	MemorySemanticsWorkgroupMemoryShift        MemorySemanticsShift = 8
	MemorySemanticsCrossWorkgroupMemoryShift   MemorySemanticsShift = 9
	MemorySemanticsAtomicCounterMemoryShift    MemorySemanticsShift = 10
	MemorySemanticsImageMemoryShift            MemorySemanticsShift = 11
	MemorySemanticsMax                         MemorySemanticsShift = 2147483647
)

// MemorySemanticsMask as declared in spirv/spirv.h:504
type MemorySemanticsMask int32

// MemorySemanticsMask enumeration from spirv/spirv.h:504
const (
	MemorySemanticsMaskNone                   MemorySemanticsMask = iota
	MemorySemanticsAcquireMask                MemorySemanticsMask = 2
	MemorySemanticsReleaseMask                MemorySemanticsMask = 4
	MemorySemanticsAcquireReleaseMask         MemorySemanticsMask = 8
	MemorySemanticsSequentiallyConsistentMask MemorySemanticsMask = 16
	MemorySemanticsUniformMemoryMask          MemorySemanticsMask = 64
	MemorySemanticsSubgroupMemoryMask         MemorySemanticsMask = 128
	MemorySemanticsWorkgroupMemoryMask        MemorySemanticsMask = 256
	MemorySemanticsCrossWorkgroupMemoryMask   MemorySemanticsMask = 512
	MemorySemanticsAtomicCounterMemoryMask    MemorySemanticsMask = 1024
	MemorySemanticsImageMemoryMask            MemorySemanticsMask = 2048
)

// MemoryAccessShift as declared in spirv/spirv.h:511
type MemoryAccessShift int32

// MemoryAccessShift enumeration from spirv/spirv.h:511
const (
	MemoryAccessVolatileShift    MemoryAccessShift = iota
	MemoryAccessAlignedShift     MemoryAccessShift = 1
	MemoryAccessNontemporalShift MemoryAccessShift = 2
	MemoryAccessMax              MemoryAccessShift = 2147483647
)

// MemoryAccessMask as declared in spirv/spirv.h:518
type MemoryAccessMask int32

// MemoryAccessMask enumeration from spirv/spirv.h:518
const (
	MemoryAccessMaskNone        MemoryAccessMask = iota
	MemoryAccessVolatileMask    MemoryAccessMask = 1
	MemoryAccessAlignedMask     MemoryAccessMask = 2
	MemoryAccessNontemporalMask MemoryAccessMask = 4
)

// Scope as declared in spirv/spirv.h:527
type Scope int32

// Scope enumeration from spirv/spirv.h:527
const (
	ScopeCrossDevice Scope = iota
	ScopeDevice      Scope = 1
	ScopeWorkgroup   Scope = 2
	ScopeSubgroup    Scope = 3
	ScopeInvocation  Scope = 4
	ScopeMax         Scope = 2147483647
)

// GroupOperation as declared in spirv/spirv.h:534
type GroupOperation int32

// GroupOperation enumeration from spirv/spirv.h:534
const (
	GroupOperationReduce        GroupOperation = iota
	GroupOperationInclusiveScan GroupOperation = 1
	GroupOperationExclusiveScan GroupOperation = 2
	GroupOperationMax           GroupOperation = 2147483647
)

// KernelEnqueueFlags as declared in spirv/spirv.h:541
type KernelEnqueueFlags int32

// KernelEnqueueFlags enumeration from spirv/spirv.h:541
const (
	KernelEnqueueFlagsNoWait        KernelEnqueueFlags = iota
	KernelEnqueueFlagsWaitKernel    KernelEnqueueFlags = 1
	KernelEnqueueFlagsWaitWorkGroup KernelEnqueueFlags = 2
	KernelEnqueueFlagsMax           KernelEnqueueFlags = 2147483647
)

// KernelProfilingInfoShift as declared in spirv/spirv.h:546
type KernelProfilingInfoShift int32

// KernelProfilingInfoShift enumeration from spirv/spirv.h:546
const (
	KernelProfilingInfoCmdExecTimeShift KernelProfilingInfoShift = iota
	KernelProfilingInfoMax              KernelProfilingInfoShift = 2147483647
)

// KernelProfilingInfoMask as declared in spirv/spirv.h:551
type KernelProfilingInfoMask int32

// KernelProfilingInfoMask enumeration from spirv/spirv.h:551
const (
	KernelProfilingInfoMaskNone        KernelProfilingInfoMask = iota
	KernelProfilingInfoCmdExecTimeMask KernelProfilingInfoMask = 1
)

// Capability as declared in spirv/spirv.h:614
type Capability int32

// Capability enumeration from spirv/spirv.h:614
const (
	CapabilityMatrix                            Capability = iota
	CapabilityShader                            Capability = 1
	CapabilityGeometry                          Capability = 2
	CapabilityTessellation                      Capability = 3
	CapabilityAddresses                         Capability = 4
	CapabilityLinkage                           Capability = 5
	CapabilityKernel                            Capability = 6
	CapabilityVector16                          Capability = 7
	CapabilityFloat16Buffer                     Capability = 8
	CapabilityFloat16                           Capability = 9
	CapabilityFloat64                           Capability = 10
	CapabilityInt64                             Capability = 11
	CapabilityInt64Atomics                      Capability = 12
	CapabilityImageBasic                        Capability = 13
	CapabilityImageReadWrite                    Capability = 14
	CapabilityImageMipmap                       Capability = 15
	CapabilityPipes                             Capability = 17
	CapabilityGroups                            Capability = 18
	CapabilityDeviceEnqueue                     Capability = 19
	CapabilityLiteralSampler                    Capability = 20
	CapabilityAtomicStorage                     Capability = 21
	CapabilityInt16                             Capability = 22
	CapabilityTessellationPointSize             Capability = 23
	CapabilityGeometryPointSize                 Capability = 24
	CapabilityImageGatherExtended               Capability = 25
	CapabilityStorageImageMultisample           Capability = 27
	CapabilityUniformBufferArrayDynamicIndexing Capability = 28
	CapabilitySampledImageArrayDynamicIndexing  Capability = 29
	CapabilityStorageBufferArrayDynamicIndexing Capability = 30
	CapabilityStorageImageArrayDynamicIndexing  Capability = 31
	CapabilityClipDistance                      Capability = 32
	CapabilityCullDistance                      Capability = 33
	CapabilityImageCubeArray                    Capability = 34
	CapabilitySampleRateShading                 Capability = 35
	CapabilityImageRect                         Capability = 36
	CapabilitySampledRect                       Capability = 37
	CapabilityGenericPointer                    Capability = 38
	CapabilityInt8                              Capability = 39
	CapabilityInputAttachment                   Capability = 40
	CapabilitySparseResidency                   Capability = 41
	CapabilityMinLod                            Capability = 42
	CapabilitySampled1D                         Capability = 43
	CapabilityImage1D                           Capability = 44
	CapabilitySampledCubeArray                  Capability = 45
	CapabilitySampledBuffer                     Capability = 46
	CapabilityImageBuffer                       Capability = 47
	CapabilityImageMSArray                      Capability = 48
	CapabilityStorageImageExtendedFormats       Capability = 49
	CapabilityImageQuery                        Capability = 50
	CapabilityDerivativeControl                 Capability = 51
	CapabilityInterpolationFunction             Capability = 52
	CapabilityTransformFeedback                 Capability = 53
	CapabilityGeometryStreams                   Capability = 54
	CapabilityStorageImageReadWithoutFormat     Capability = 55
	CapabilityStorageImageWriteWithoutFormat    Capability = 56
	CapabilityMultiViewport                     Capability = 57
	CapabilitySubgroupDispatch                  Capability = 58
	CapabilityNamedBarrier                      Capability = 59
	CapabilityPipeStorage                       Capability = 60
	CapabilityMax                               Capability = 2147483647
)

// Op as declared in spirv/spirv.h:922
type Op int32

// Op enumeration from spirv/spirv.h:922
const (
	OpNop                                     Op = iota
	OpUndef                                   Op = 1
	OpSourceContinued                         Op = 2
	OpSource                                  Op = 3
	OpSourceExtension                         Op = 4
	OpName                                    Op = 5
	OpMemberName                              Op = 6
	OpString                                  Op = 7
	OpLine                                    Op = 8
	OpExtension                               Op = 10
	OpExtInstImport                           Op = 11
	OpExtInst                                 Op = 12
	OpMemoryModel                             Op = 14
	OpEntryPoint                              Op = 15
	OpExecutionMode                           Op = 16
	OpCapability                              Op = 17
	OpTypeVoid                                Op = 19
	OpTypeBool                                Op = 20
	OpTypeInt                                 Op = 21
	OpTypeFloat                               Op = 22
	OpTypeVector                              Op = 23
	OpTypeMatrix                              Op = 24
	OpTypeImage                               Op = 25
	OpTypeSampler                             Op = 26
	OpTypeSampledImage                        Op = 27
	OpTypeArray                               Op = 28
	OpTypeRuntimeArray                        Op = 29
	OpTypeStruct                              Op = 30
	OpTypeOpaque                              Op = 31
	OpTypePointer                             Op = 32
	OpTypeFunction                            Op = 33
	OpTypeEvent                               Op = 34
	OpTypeDeviceEvent                         Op = 35
	OpTypeReserveId                           Op = 36
	OpTypeQueue                               Op = 37
	OpTypePipe                                Op = 38
	OpTypeForwardPointer                      Op = 39
	OpConstantTrue                            Op = 41
	OpConstantFalse                           Op = 42
	OpConstant                                Op = 43
	OpConstantComposite                       Op = 44
	OpConstantSampler                         Op = 45
	OpConstantNull                            Op = 46
	OpSpecConstantTrue                        Op = 48
	OpSpecConstantFalse                       Op = 49
	OpSpecConstant                            Op = 50
	OpSpecConstantComposite                   Op = 51
	OpSpecConstantOp                          Op = 52
	OpFunction                                Op = 54
	OpFunctionParameter                       Op = 55
	OpFunctionEnd                             Op = 56
	OpFunctionCall                            Op = 57
	OpVariable                                Op = 59
	OpImageTexelPointer                       Op = 60
	OpLoad                                    Op = 61
	OpStore                                   Op = 62
	OpCopyMemory                              Op = 63
	OpCopyMemorySized                         Op = 64
	OpAccessChain                             Op = 65
	OpInBoundsAccessChain                     Op = 66
	OpPtrAccessChain                          Op = 67
	OpArrayLength                             Op = 68
	OpGenericPtrMemSemantics                  Op = 69
	OpInBoundsPtrAccessChain                  Op = 70
	OpDecorate                                Op = 71
	OpMemberDecorate                          Op = 72
	OpDecorationGroup                         Op = 73
	OpGroupDecorate                           Op = 74
	OpGroupMemberDecorate                     Op = 75
	OpVectorExtractDynamic                    Op = 77
	OpVectorInsertDynamic                     Op = 78
	OpVectorShuffle                           Op = 79
	OpCompositeConstruct                      Op = 80
	OpCompositeExtract                        Op = 81
	OpCompositeInsert                         Op = 82
	OpCopyObject                              Op = 83
	OpTranspose                               Op = 84
	OpSampledImage                            Op = 86
	OpImageSampleImplicitLod                  Op = 87
	OpImageSampleExplicitLod                  Op = 88
	OpImageSampleDrefImplicitLod              Op = 89
	OpImageSampleDrefExplicitLod              Op = 90
	OpImageSampleProjImplicitLod              Op = 91
	OpImageSampleProjExplicitLod              Op = 92
	OpImageSampleProjDrefImplicitLod          Op = 93
	OpImageSampleProjDrefExplicitLod          Op = 94
	OpImageFetch                              Op = 95
	OpImageGather                             Op = 96
	OpImageDrefGather                         Op = 97
	OpImageRead                               Op = 98
	OpImageWrite                              Op = 99
	OpImage                                   Op = 100
	OpImageQueryFormat                        Op = 101
	OpImageQueryOrder                         Op = 102
	OpImageQuerySizeLod                       Op = 103
	OpImageQuerySize                          Op = 104
	OpImageQueryLod                           Op = 105
	OpImageQueryLevels                        Op = 106
	OpImageQuerySamples                       Op = 107
	OpConvertFToU                             Op = 109
	OpConvertFToS                             Op = 110
	OpConvertSToF                             Op = 111
	OpConvertUToF                             Op = 112
	OpUConvert                                Op = 113
	OpSConvert                                Op = 114
	OpFConvert                                Op = 115
	OpQuantizeToF16                           Op = 116
	OpConvertPtrToU                           Op = 117
	OpSatConvertSToU                          Op = 118
	OpSatConvertUToS                          Op = 119
	OpConvertUToPtr                           Op = 120
	OpPtrCastToGeneric                        Op = 121
	OpGenericCastToPtr                        Op = 122
	OpGenericCastToPtrExplicit                Op = 123
	OpBitcast                                 Op = 124
	OpSNegate                                 Op = 126
	OpFNegate                                 Op = 127
	OpIAdd                                    Op = 128
	OpFAdd                                    Op = 129
	OpISub                                    Op = 130
	OpFSub                                    Op = 131
	OpIMul                                    Op = 132
	OpFMul                                    Op = 133
	OpUDiv                                    Op = 134
	OpSDiv                                    Op = 135
	OpFDiv                                    Op = 136
	OpUMod                                    Op = 137
	OpSRem                                    Op = 138
	OpSMod                                    Op = 139
	OpFRem                                    Op = 140
	OpFMod                                    Op = 141
	OpVectorTimesScalar                       Op = 142
	OpMatrixTimesScalar                       Op = 143
	OpVectorTimesMatrix                       Op = 144
	OpMatrixTimesVector                       Op = 145
	OpMatrixTimesMatrix                       Op = 146
	OpOuterProduct                            Op = 147
	OpDot                                     Op = 148
	OpIAddCarry                               Op = 149
	OpISubBorrow                              Op = 150
	OpUMulExtended                            Op = 151
	OpSMulExtended                            Op = 152
	OpAny                                     Op = 154
	OpAll                                     Op = 155
	OpIsNan                                   Op = 156
	OpIsInf                                   Op = 157
	OpIsFinite                                Op = 158
	OpIsNormal                                Op = 159
	OpSignBitSet                              Op = 160
	OpLessOrGreater                           Op = 161
	OpOrdered                                 Op = 162
	OpUnordered                               Op = 163
	OpLogicalEqual                            Op = 164
	OpLogicalNotEqual                         Op = 165
	OpLogicalOr                               Op = 166
	OpLogicalAnd                              Op = 167
	OpLogicalNot                              Op = 168
	OpSelect                                  Op = 169
	OpIEqual                                  Op = 170
	OpINotEqual                               Op = 171
	OpUGreaterThan                            Op = 172
	OpSGreaterThan                            Op = 173
	OpUGreaterThanEqual                       Op = 174
	OpSGreaterThanEqual                       Op = 175
	OpULessThan                               Op = 176
	OpSLessThan                               Op = 177
	OpULessThanEqual                          Op = 178
	OpSLessThanEqual                          Op = 179
	OpFOrdEqual                               Op = 180
	OpFUnordEqual                             Op = 181
	OpFOrdNotEqual                            Op = 182
	OpFUnordNotEqual                          Op = 183
	OpFOrdLessThan                            Op = 184
	OpFUnordLessThan                          Op = 185
	OpFOrdGreaterThan                         Op = 186
	OpFUnordGreaterThan                       Op = 187
	OpFOrdLessThanEqual                       Op = 188
	OpFUnordLessThanEqual                     Op = 189
	OpFOrdGreaterThanEqual                    Op = 190
	OpFUnordGreaterThanEqual                  Op = 191
	OpShiftRightLogical                       Op = 194
	OpShiftRightArithmetic                    Op = 195
	OpShiftLeftLogical                        Op = 196
	OpBitwiseOr                               Op = 197
	OpBitwiseXor                              Op = 198
	OpBitwiseAnd                              Op = 199
	OpNot                                     Op = 200
	OpBitFieldInsert                          Op = 201
	OpBitFieldSExtract                        Op = 202
	OpBitFieldUExtract                        Op = 203
	OpBitReverse                              Op = 204
	OpBitCount                                Op = 205
	OpDPdx                                    Op = 207
	OpDPdy                                    Op = 208
	OpFwidth                                  Op = 209
	OpDPdxFine                                Op = 210
	OpDPdyFine                                Op = 211
	OpFwidthFine                              Op = 212
	OpDPdxCoarse                              Op = 213
	OpDPdyCoarse                              Op = 214
	OpFwidthCoarse                            Op = 215
	OpEmitVertex                              Op = 218
	OpEndPrimitive                            Op = 219
	OpEmitStreamVertex                        Op = 220
	OpEndStreamPrimitive                      Op = 221
	OpControlBarrier                          Op = 224
	OpMemoryBarrier                           Op = 225
	OpAtomicLoad                              Op = 227
	OpAtomicStore                             Op = 228
	OpAtomicExchange                          Op = 229
	OpAtomicCompareExchange                   Op = 230
	OpAtomicCompareExchangeWeak               Op = 231
	OpAtomicIIncrement                        Op = 232
	OpAtomicIDecrement                        Op = 233
	OpAtomicIAdd                              Op = 234
	OpAtomicISub                              Op = 235
	OpAtomicSMin                              Op = 236
	OpAtomicUMin                              Op = 237
	OpAtomicSMax                              Op = 238
	OpAtomicUMax                              Op = 239
	OpAtomicAnd                               Op = 240
	OpAtomicOr                                Op = 241
	OpAtomicXor                               Op = 242
	OpPhi                                     Op = 245
	OpLoopMerge                               Op = 246
	OpSelectionMerge                          Op = 247
	OpLabel                                   Op = 248
	OpBranch                                  Op = 249
	OpBranchConditional                       Op = 250
	OpSwitch                                  Op = 251
	OpKill                                    Op = 252
	OpReturn                                  Op = 253
	OpReturnValue                             Op = 254
	OpUnreachable                             Op = 255
	OpLifetimeStart                           Op = 256
	OpLifetimeStop                            Op = 257
	OpGroupAsyncCopy                          Op = 259
	OpGroupWaitEvents                         Op = 260
	OpGroupAll                                Op = 261
	OpGroupAny                                Op = 262
	OpGroupBroadcast                          Op = 263
	OpGroupIAdd                               Op = 264
	OpGroupFAdd                               Op = 265
	OpGroupFMin                               Op = 266
	OpGroupUMin                               Op = 267
	OpGroupSMin                               Op = 268
	OpGroupFMax                               Op = 269
	OpGroupUMax                               Op = 270
	OpGroupSMax                               Op = 271
	OpReadPipe                                Op = 274
	OpWritePipe                               Op = 275
	OpReservedReadPipe                        Op = 276
	OpReservedWritePipe                       Op = 277
	OpReserveReadPipePackets                  Op = 278
	OpReserveWritePipePackets                 Op = 279
	OpCommitReadPipe                          Op = 280
	OpCommitWritePipe                         Op = 281
	OpIsValidReserveId                        Op = 282
	OpGetNumPipePackets                       Op = 283
	OpGetMaxPipePackets                       Op = 284
	OpGroupReserveReadPipePackets             Op = 285
	OpGroupReserveWritePipePackets            Op = 286
	OpGroupCommitReadPipe                     Op = 287
	OpGroupCommitWritePipe                    Op = 288
	OpEnqueueMarker                           Op = 291
	OpEnqueueKernel                           Op = 292
	OpGetKernelNDrangeSubGroupCount           Op = 293
	OpGetKernelNDrangeMaxSubGroupSize         Op = 294
	OpGetKernelWorkGroupSize                  Op = 295
	OpGetKernelPreferredWorkGroupSizeMultiple Op = 296
	OpRetainEvent                             Op = 297
	OpReleaseEvent                            Op = 298
	OpCreateUserEvent                         Op = 299
	OpIsValidEvent                            Op = 300
	OpSetUserEventStatus                      Op = 301
	OpCaptureEventProfilingInfo               Op = 302
	OpGetDefaultQueue                         Op = 303
	OpBuildNDRange                            Op = 304
	OpImageSparseSampleImplicitLod            Op = 305
	OpImageSparseSampleExplicitLod            Op = 306
	OpImageSparseSampleDrefImplicitLod        Op = 307
	OpImageSparseSampleDrefExplicitLod        Op = 308
	OpImageSparseSampleProjImplicitLod        Op = 309
	OpImageSparseSampleProjExplicitLod        Op = 310
	OpImageSparseSampleProjDrefImplicitLod    Op = 311
	OpImageSparseSampleProjDrefExplicitLod    Op = 312
	OpImageSparseFetch                        Op = 313
	OpImageSparseGather                       Op = 314
	OpImageSparseDrefGather                   Op = 315
	OpImageSparseTexelsResident               Op = 316
	OpNoLine                                  Op = 317
	OpAtomicFlagTestAndSet                    Op = 318
	OpAtomicFlagClear                         Op = 319
	OpImageSparseRead                         Op = 320
	OpSizeOf                                  Op = 321
	OpTypePipeStorage                         Op = 322
	OpConstantPipeStorage                     Op = 323
	OpCreatePipeFromPipeStorage               Op = 324
	OpGetKernelLocalSizeForSubgroupCount      Op = 325
	OpGetKernelMaxNumSubgroups                Op = 326
	OpTypeNamedBarrier                        Op = 327
	OpNamedBarrierInitialize                  Op = 328
	OpMemoryNamedBarrier                      Op = 329
	OpModuleProcessed                         Op = 330
	OpMax                                     Op = 2147483647
)
