// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 02 Mar 2016 22:58:24 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package spirv provides Go bindings for spirv.h
*/
package spirv
