// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 16 May 2016 03:39:46 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package spirv provides Go bindings for spirv.h
*/
package spirv
