// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 05 Mar 2016 20:44:59 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package spirv provides Go bindings for spirv.h
*/
package spirv
