// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 02 May 2017 21:32:37 EEST.
// By https://git.io/c-for-go. DO NOT EDIT.

package spirv

// Id type as declared in spirv/spirv.h:51
type Id uint32
