// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 05 Mar 2016 21:49:44 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package spirv

// Id type as declared in spirv/spirv.h:51
type Id uint32
