// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 16 May 2016 03:39:46 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package spirv

// Id type as declared in spirv/spirv.h:51
type Id uint32
