// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 22 Aug 2020 12:36:44 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package spirv provides Go bindings for spirv.h
*/
package spirv
