// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 22 Aug 2020 12:36:44 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package spirv

// Id type as declared in spv/spirv.h:54
type Id uint32
