// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 22 Aug 2020 12:36:45 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package glsl provides Go bindings for GLSL.std.450.h
*/
package glsl
